version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}  # Change this in production
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7701:7700"
    command: meilisearch --env development

volumes:
  meili_data:
